apiVersion: v1
kind: Service
metadata:
  name:  demo-rtp-service
  namespace: demo-dev
spec:
  type: NodePort
  selector:
    app: demo-rtp
  ports:
  - nodePort: 30082
    port: 8000
    targetPort: 8000
